modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="alcocraftplus"
version="${file.jarVersion}"
displayName="Alcocraft"
logoFile="alcocraftplus.png"
credits="Original AlcoCraft mod by hadrus"
authors="itzme1on, CCr4ft3r, David Frederick Batt"
description='''
With this mod you will be able to brew beer and treat your good friends with it!
'''
[[dependencies.alcocraftplus]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alcocraftplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"